### ISSUE TITLE
Linear dynamic from `linear_model_setup()`, matrix power instead of multiplication.

### ISSUE THREAD

**Issue by xhu4** [nansencenter/DAPPER#10]
Currently the `linear_model_setup` defines the `model` and `jacob` method as
```
  def model(x,t,dt): return dt*(ModelMatrix@x)
  def jacob(x,t,dt): return dt*ModelMatrix
```

If I understand it correctly, shouldn't it be something like this?
```
  def model(x,t,dt): return np.linalg.matrix_power(ModelMatrix, dt) @ x
  def jacob(x,t,dt): return np.linalg.matrix_power(ModelMatrix, dt)
```

**Comment by patricknraanes** [comment]
Yes, that would be better. There are complications:
* Avoiding re-computing the matrix powers for each time step
* Only integer powers of matrices are uniquely defined
This has been taken care of in this patch: https://github.com/nansencenter/DAPPER/commit/83ee9df6d657bbcdc39d73794eec15ab78a96b2b
