### ISSUE TITLE
FVCOM assimilation of tide gauge station data

### ISSUE THREAD

**Issue by q1165600785** [nansencenter/DAPPER#110]
I use the FVCOM model to simulate a tidal model for a region. When I obtain the simulation results, can I use this Python package to assimilate them with the long-term historical water level data of the tidal station        
Can I do this?

**Comment by patnr** [comment]
Maybe, maybe not.

Here is a short guide to help you determine the answer:
https://github.com/nansencenter/DAPPER?tab=readme-ov-file#similar-projects
