### ISSUE TITLE
Issue when length=1 1D array is returned from observation function

### ISSUE THREAD

**Issue by TobiasGlaubach** [nansencenter/DAPPER#12]
Hi, 
first of all, thanks for the amazing software you build, all the work you put into it as well as making it open source for everyone. 

When familiarizing myself with the software using a very simple model like this:

```
# measurement function: sample polynomial by time
@ens_compatible
def hxt(x, t):
    # case x is 1-dimensional (as in the simulation part)
    if len(x.shape) == 1:
        r = x[0]*t**2 + x[1] * t + x[2]
    else: # case of N different parameters (ensemble)
        r = x[0,:]*t**2 + x[1,:] * t + x[2,:]
    return r

@ens_compatible
def model_step(x0, t0, dt):
    return x0

# write the function for model state update in an Operator class compatible dict
Dyn = {
    'M': Nx,
    'model': step,
    'noise': 0
    }

# write the measurement function which maps states to observations to an Operator class compatible dict
Obs = {
    'M': 1,
    'model': NamedFunc(hxt, 'MapStatesP'),
    'noise': 1.5
    }

```

I get an error in the EnKF function. However, if I artificially return a length 2 1-D array by returning r twice, the model works fine. 

Am I doing something wrong, or is that a bug?

I will give detailed error info later, since I do not have full access to my system and codes.

**Comment by patricknraanes** [comment]
Hi Tobias!

You should not loose dimensions:
if x is 1d (resp. 2d),
you must return a 1d (resp. 2d) array.

Here's what I think is a possible solution.

```
@ens_compatible
def hxt(x, t):
    r = x[[0]] + x[[1]] + x[[2]]
    return r

def model_step(x0, t0, dt):
    return x0
```

Additional comments:
I have removed the 2nd case (thanks to the magic of `ens_compatible`).
But I have also removed this decorator on model_step, where it is not needed.
