### ISSUE TITLE
ModuleNotFoundError: No module named 'dill'

### ISSUE THREAD

**Issue by fengzhoushui** [nansencenter/DAPPER#13]
Thank u for your project.How could I resolve this error?
`from resources.workspace import *`

Initializing DAPPER...
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3051481c9fff> in <module>
      1 # Run this cell now.
----> 2 from resources.workspace import *

E:\projectsSpace\pythonspace\DA-tutorials-master\resources\workspace.py in <module>
      6 
      7 # Load DAPPER
----> 8 from dapper import *
      9 
     10 # Load answers

e:\projectsspace\pythonspace\dapper-master\dapper\__init__.py in <module>
    155 from .tools.data_management import *
    156 from .stats import *
--> 157 from .admin import *
    158 from .da_methods.ensemble import *
    159 from .da_methods.particle import *

e:\projectsspace\pythonspace\dapper-master\dapper\admin.py in <module>
    549 
    550 
--> 551 import dill
    552 def save_data(name,*args,**kwargs):
    553   """"Utility for saving experimental data.

ModuleNotFoundError: No module named 'dill'

**Comment by patricknraanes** [comment]
Try running:
pip install dill
