### ISSUE TITLE
Liveplot splitting then Joint Estimation

### ISSUE THREAD

**Issue by onlyname0** [nansencenter/DAPPER#14]
Take for example_1.py: 
1. How did you get the sliding_marginals to return x,y,z separately? Have you hard-coded params labels='xyz' to plot x,y,z separately? Otherwise would it handle slices as well?
2. Could spatial1d handle slices? e.g. plot just x,y or [x,y] with a constant array like [0,1] 
Suppose you want to Jointly estimate the state and parameters, i.e. [x,y,z,sig,rho,beta] is the new model output.
3. Can you separate sig, rho, beta easily/omit them from live plotting?

Much Appreciated!

**Comment by patricknraanes** [comment]
1. sliding_marginals is attached to the L63 experiment in the HMM setup in dapper/mods/Lorenz63/core.py . There, the dimensions are explicitly labelled "xyz".
 2. sliding_marginals is defined in dapper/tools/liveplotting.py . You can see that it takes "dims" and "labels" as input parameters. From the code, it seems that dims can be a list (not range) of dimension indices. If the parameters are part of the state vectors, then they can be plotted just like the other state dimensions.
 3. However, you have to do deeper modifications to separate the plot of the parameters from that of the state.
