### ISSUE TITLE
Do you have any benchmark for handling corrupt data sources?

### ISSUE THREAD

**Issue by denfromufa** [nansencenter/DAPPER#2]
I'm very new to DA. Is data corruption (out of bounds, drift, frozen state) modeled in DA? For example multiple measurements of the same observation, where few of them may drop out.

**Comment by patricknraanes** [comment]
The field of DA typically operates with dynamical and observational models as "black boxes", meaning that their correct-ness is assumed up to an error that is modelled as white noise, with pre-specified statistics. Typically their covariance matrices are labelled Q and R. If Q and R are wrong, or the errors take a particularly non-Gaussian form, the DA output will be faulty. Sometimes "adaptive" DA methods try to automatically adjust for it, but the potential is limited.

**Comment by denfromufa** [comment]
Thank you for clarifying, this makes total sense.
