### ISSUE TITLE
Running On windows

### ISSUE THREAD

**Issue by Himscipy** [nansencenter/DAPPER#3]
Hello,

I am trying to run the Dapper with Windows and receiving following error.

`Truth & Obs: 100%|██████████████████████████████████████████████████████████████| 3000/3000 [00:00<00:00, 14237.16it/s]                                                                                                                     Initializing liveplotting...                                                                                          Press <Enter> to toggle live plot ON/OFF.                                                                             Press <Space> and then <Enter> to pause.                                                                              EnKF:   0%|                                                                                   | 0/3000 [00:00<?, ?it/s]                                                                                                                     Traceback (most recent call last):                                                                                      File "example_1.py", line 17, in <module>                                                                               stats = config.assimilate(setup,xx,yy)                                                                              File "U:\Project_Dapper\DAPPER-master\DAPPER-master\tools\admin.py", line 99, in assim_caller                           assimilator(stats,setup,xx,yy)                                                                                      File "U:\Project_Dapper\DAPPER-master\DAPPER-master\da_methods.py", line 32, in assimilator                             stats.assess(k,kObs,E=E)                                                                                            File "U:\Project_Dapper\DAPPER-master\DAPPER-master\stats.py", line 142, in assess                                      self.lplot.update(k,kObs,**state_prms)                                                                              File "U:\Project_Dapper\DAPPER-master\DAPPER-master\tools\viz.py", line 448, in update                                  if self.skip_plotting(): return                                                                                     File "U:\Project_Dapper\DAPPER-master\DAPPER-master\tools\viz.py", line 433, in skip_plotting                           key = poll_input() # =None if <space> was pressed above                                                             File "U:\Project_Dapper\DAPPER-master\DAPPER-master\tools\utils.py", line 62, in poll_input                             i,o,e = select.select([sys.stdin],[],[],0.0001)                                                                   OSError: [WinError 10038] An operation was attempted on something that is not a socket ` 

Let me know if there are some other settings which are required to be done to run Dapper with windows-10.

Thank you

**Comment by patricknraanes** [comment]
Seems to be a bug. Until it's fixed, you'll have do turn liveplotting off. I.e. use this in example_1.py:

config = EnKF('Sqrt', N=10, infl=1.02, rot=True, liveplotting=False)

**Comment by Himscipy** [comment]
Thanks for the quick response. I guessed it and did turned it off and it worked.

**Comment by patricknraanes** [comment]
Hi. I believe this should be working properly now.
