### ISSUE TITLE
Travis CI changed its pricing policy

### ISSUE THREAD

**Issue by aperrin66** [nansencenter/DAPPER#71]
Travis CI has changed its pricing policy. It is no longer free for public repositories (without negotiating).
In consequence, the `nansencenter` organization has been switched to a trial plan with limited credit that will not be renewed, so it is necessary to move to another CI provider.

Most of the other [nansencenter](https://github.com/nansencenter) repositories are being switched to [Github Actions](https://docs.github.com/en/actions). I can provide help with that if needed.

**Comment by patricknraanes** [comment]
Hi, and many thanks for the notification, and the offer of assistance. If you have the time, I'd very much welcome a PR. Otherwise I will reach out when we get started on this in case we need assistance.
