### ISSUE TITLE
DA multilayer shallow water 

### ISSUE THREAD

**Issue by apatlpo** [nansencenter/DAPPER#8]
Hi,

I am working on setting up a parallelized (MPI) python multilayer shallow water code and would like eventually to do DA with it. 

The typical problems I will look at will have state vectors of the following size approx.: 10 vars x O(1000)^2 grid points.

Will I be able to use dapper to do that?
If yes, what should I look for when setting up the code
If not, what would be a good alternative?

Disclaimer I am a physical oceanographer and not a DA expert.

cheers

**Comment by patricknraanes** [comment]
I have not tried such a big problem, but I believe it should be possible. Have a look at the QG model (Quasi-Geostrophic) for an example. Otherwise see https://github.com/nansencenter/DAPPER#alternative-projects
