### ISSUE TITLE
Make "Persistence" da_method

### ISSUE THREAD

**Issue by patricknraanes** [nansencenter/DAPPER#84]
This should use the truth at the previous analysis time for the following forecast and analysis.

**Comment by Balinus** [comment]
This is a good idea to have such method, as a form of baseline for some application. How hard it would be to have the flexibility to add a covariable modulating the persistence? For example, if I have radiation data at 10h AM and want to "persist" the data to t+1h, I would be interested to multiply the last value by the theoretical clear sky values (e.g. I know there should be more radiation at 11h, given constant clouds composition and opacity).

So perhaps put simply, a form of "Smart Persistence" ?

I would like to take the time to congratulate you and the team on developing this package. We are looking at it for a research use in Hydrology.

**Comment by patricknraanes** [comment]
Closed by https://github.com/nansencenter/DAPPER/commit/5783ed2bbb20c71c87424bb2fb75cb747d73c7d6

Also made a method called `PreProg`.

I think you should be able to combine `Persistence` and `PreProg` somehow to get what you want (probably the easiest is simply to use them as inspiration for a new da_method class).

Thank you for the kind words.
