### ISSUE TITLE
run time error in example_3.py

### ISSUE THREAD

**Issue by didiermonselesan** [nansencenter/DAPPER#9]
The installation and tests of DAPPER on ubuntu 16.04 LTS (conda/anaconda python 3.7) was performed. The first two example_1.py and example_2.py run without any issues. But both example_3.py F and N did not complete. Both return an error in LETKF executions, where loc_rad='$' (F run) or N='?' and loc_rad='? (N run) it seems.
----------------------------------------------------------------------------------------------------------------------
(py37) mon137@smudge-hf:~/projects/v14/python_work/DAPPER$ python -i example_3.py N
Initializing DAPPER...Done
Will save to data/example_3/smudge-hf/N_run3...
 
xticks[0/831] N: 2
Truth & Obs: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:01<00:00, 4944.07it/s]
Climatology: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:04<00:00, 1166.58it/s]
OptInterp: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:08<00:00, 639.15it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:11<00:00, 427.32it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:12<00:00, 409.30it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:13<00:00, 382.22it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:13<00:00, 389.10it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:12<00:00, 409.30it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:12<00:00, 397.79it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:14<00:00, 347.07it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:14<00:00, 342.55it/s]
EnKF_N: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:17<00:00, 292.61it/s]
EnKF_N: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:17<00:00, 289.62it/s]
LETKF: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:38<00:00, 134.29it/s]
LETKF:   0%|                                                                                                                                       | 0/5120 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "example_3.py", line 127, in <module>
    stat = C.assimilate(HMM,xx,yy)
  File "/home/mon137/projects/v14/python_work/DAPPER/da_methods/admin.py", line 139, in assim_caller
    raise ERR
  File "/home/mon137/projects/v14/python_work/DAPPER/da_methods/admin.py", line 120, in assim_caller
    assimilator(stats,HMM,xx,yy)
  File "/home/mon137/projects/v14/python_work/DAPPER/da_methods/da_methods.py", line 612, in assimilator
    for ii, (Eii, za) in zip(state_batches, result):
TypeError: 'NoneType' object is not iterable
>>> exit()
----------------------------------------------------------------------------------------------------------------------
(py37) mon137@smudge-hf:~/projects/v14/python_work/DAPPER$ python -i example_3.py F
Initializing DAPPER...Done
Will save to data/example_3/smudge-hf/F_run4...
 
xticks[0/543] F: 3
Truth & Obs: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:01<00:00, 5057.07it/s]
Climatology: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:04<00:00, 1058.39it/s]
OptInterp: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:08<00:00, 586.09it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:15<00:00, 336.81it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:15<00:00, 325.71it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:15<00:00, 332.34it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:16<00:00, 319.30it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:15<00:00, 332.05it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:15<00:00, 328.55it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:15<00:00, 325.31it/s]
EnKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:15<00:00, 321.57it/s]
EnKF_N: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:16<00:00, 313.47it/s]
EnKF_N: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:16<00:00, 317.52it/s]
LETKF: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:45<00:00, 113.07it/s]
LETKF: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [00:40<00:00, 126.30it/s]
LETKF: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5120/5120 [01:06<00:00, 76.47it/s]
LETKF:   0%|                                                                                                                                       | 0/5120 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "example_3.py", line 127, in <module>
    stat = C.assimilate(HMM,xx,yy)
  File "/home/mon137/projects/v14/python_work/DAPPER/da_methods/admin.py", line 139, in assim_caller
    raise ERR
  File "/home/mon137/projects/v14/python_work/DAPPER/da_methods/admin.py", line 120, in assim_caller
    assimilator(stats,HMM,xx,yy)
  File "/home/mon137/projects/v14/python_work/DAPPER/da_methods/da_methods.py", line 612, in assimilator
    for ii, (Eii, za) in zip(state_batches, result):
  File "/home/mon137/projects/v14/python_work/DAPPER/da_methods/da_methods.py", line 580, in local_analysis
    jj, tapering = obs_localizer(ii)
  File "/home/mon137/projects/v14/python_work/DAPPER/tools/localization.py", line 188, in obs_localizer
    return inds_and_coeffs(dists, radius, tag=tag)
  File "/home/mon137/projects/v14/python_work/DAPPER/tools/localization.py", line 94, in inds_and_coeffs
    coeffs = dist2coeff(dists, radius, tag)
  File "/home/mon137/projects/v14/python_work/DAPPER/tools/localization.py", line 63, in dist2coeff
    R = radius * 1.82 # Sakov: 1.7386
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by patricknraanes** [comment]
The 1st issue (now fixed) was that the implementation of state "batches" for the local analysis resulted in batches with no obs (and because tapering was measured from center), and that this was not handled properly in the algorithm.

The 2nd issue (now fixed) was that CtrlVar F and loc_rad='$' yielded no actual loc_rad because I had forgotten to specify it.
